### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by theboss388** [cfjedimaster/brackets-w3cvalidation#24]
OSX Yosemite.

I have installed the extension, closed brackets down and reopened and I see no icons, yellow green or otherwise at the bottom of my documents.

Any ideas?

**Comment by cfjedimaster** [comment]
If you open the developer console, do you see an error?

**Comment by theboss388** [comment]
![brackets-dev-console](https://cloud.githubusercontent.com/assets/8142676/6573247/070fddb6-c711-11e4-84fc-4cc68078ad4e.jpg)
 This is what I get in the developer console

**Comment by cfjedimaster** [comment]
And you have a .html file open?

**Comment by theboss388** [comment]
I actually had a .php file open. Have just tried with a .html file, and it works fine.

Presumably, this doesn't work with .php files, only .html?

**Comment by cfjedimaster** [comment]
Correct.

On Tue, Mar 10, 2015 at 5:38 AM, theboss388 <notifications@github.com>
wrote:

> I actually had a .php file open. Have just tried with a .html file, and it
> works fine.
>
> Presumably, this doesn't work with .php files, only .html?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cfjedimaster/brackets-w3cvalidation/issues/24#issuecomment-78029844>
> .
>



-- 
===========================================================================
Raymond Camden, Developer Advocate for MobileFirst at IBM

Email : raymondcamden@gmail.com
Blog : www.raymondcamden.com
Twitter: raymondcamden

**Comment by theboss388** [comment]
Explains it then :)

Cheers!
