### ISSUE TITLE
Validator broken as of Today (8 June 2015)

### ISSUE THREAD

**Issue by claudericke** [cfjedimaster/brackets-w3cvalidation#29]
The validator plug in is now reporting the following errorL

This interface to HTML5 checking is deprecated. Use the Nu HTML Checker at https://validator.w3.org/nu/ directly instead.

**Comment by cfjedimaster** [comment]
Fixed. (Technically fixed in 60 seconds when I commit.)

**Comment by ZKjellberg** [comment]
Current version available through Brackets is 2.1.9. https://brackets-registry.aboutweb.com/

Is there a delay for having the extension updated?

**Comment by cfjedimaster** [comment]
Yeah the registry was down earlier. I'll chedk.

On Mon, Jun 8, 2015 at 6:37 PM, Zachary Kjellberg <notifications@github.com>
wrote:

> Current version available through Brackets is 2.1.9.
> https://brackets-registry.aboutweb.com/
>
> Is there a delay for having the extension updated?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cfjedimaster/brackets-w3cvalidation/issues/29#issuecomment-110172085>
> .
>



-- 
===========================================================================
Raymond Camden, Developer Advocate for MobileFirst at IBM

Email : raymondcamden@gmail.com
Blog : www.raymondcamden.com
Twitter: raymondcamden

**Comment by cfjedimaster** [comment]
Done

On Mon, Jun 8, 2015 at 6:44 PM, Raymond Camden <raymondcamden@gmail.com>
wrote:

> Yeah the registry was down earlier. I'll chedk.
>
> On Mon, Jun 8, 2015 at 6:37 PM, Zachary Kjellberg <
> notifications@github.com> wrote:
>
>> Current version available through Brackets is 2.1.9.
>> https://brackets-registry.aboutweb.com/
>>
>> Is there a delay for having the extension updated?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/cfjedimaster/brackets-w3cvalidation/issues/29#issuecomment-110172085>
>> .
>>
>
>
>
> --
> ===========================================================================
> Raymond Camden, Developer Advocate for MobileFirst at IBM
>
> Email : raymondcamden@gmail.com
> Blog : www.raymondcamden.com
> Twitter: raymondcamden
>



-- 
===========================================================================
Raymond Camden, Developer Advocate for MobileFirst at IBM

Email : raymondcamden@gmail.com
Blog : www.raymondcamden.com
Twitter: raymondcamden
