### ISSUE TITLE
HTML5 Checking Deprecated

### ISSUE THREAD

**Issue by thatvideoshopguy** [cfjedimaster/brackets-w3cvalidation#31]
Hi Raymond,

Thanks for the work on plugging the W3C validator API into a Brackets Extension. Currently there is an error message on the validator that says "This interface to HTML5 document checking is deprecated."

From a [StackOverflow Question] (http://stackoverflow.com/questions/30716156/this-interface-to-html5-document-checking-is-deprecated-whats-the-meaning) response it looks like it's probably a W3C issue, but just wanted to note it in case there's something you can do from your side.

Cheers,
Kyle

![problem](https://cloud.githubusercontent.com/assets/9395037/8085546/046ba70c-0f91-11e5-83dd-4f82955305ee.jpg)

**Comment by cfjedimaster** [comment]
I just fixed this yesterday - are you running the latest version?

On Wed, Jun 10, 2015 at 9:52 AM, Kyle <notifications@github.com> wrote:

> Hi Raymond,
>
> Thanks for the work on plugging the W3C validator API into a Brackets
> Extension. Currently there is an error message on the validator that says
> "This interface to HTML5 document checking is deprecated."
>
> From a StackOverflow Question
> <http://stackoverflow.com/questions/30716156/this-interface-to-html5-document-checking-is-deprecated-whats-the-meaning>
> response it looks like it's probably a W3C issue, but just wanted to note
> it in case there's something you can do from your side.
>
> Cheers,
> Kyle
>
> [image: problem]
> <https://cloud.githubusercontent.com/assets/9395037/8085546/046ba70c-0f91-11e5-83dd-4f82955305ee.jpg>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cfjedimaster/brackets-w3cvalidation/issues/31>.
>



-- 
===========================================================================
Raymond Camden, Developer Advocate for MobileFirst at IBM

Email : raymondcamden@gmail.com
Blog : www.raymondcamden.com
Twitter: raymondcamden

**Comment by thatvideoshopguy** [comment]
I just did a refresh of Brackets and the update popped up. Thanks.
