### ISSUE TITLE
always shows warnings after new update

### ISSUE THREAD

**Issue by francis-zhu-cloudpense** [cfjedimaster/brackets-w3cvalidation#33]
Yes, I can validate again after the update.

However, all previously valid file now turns up with "2 W3CValidation Problems", namely
```
The Content-Type was “text/html”. Using the HTML parser.
Using the schema for HTML with SVG 1.1, MathML 3.0, RDFa 1.1, and ITS 2.0 support.	
```

How can I turn this off?

A sample HTML file is something like this:

```html
<!doctype html>
<html>
  <head>
    <meta charset='utf-8'>
    <title>Test</title>
  </head>
  <body>
    <h1>Hello, World!</h1>
  </body>
</html>
```

**Comment by cfjedimaster** [comment]
I believe those are just informational type messages. Let me see if I can ignore them.

**Comment by cfjedimaster** [comment]
Wow - and now the validator is blocking me from using it due to "abuse". This may be the end of the validator.

**Comment by jakman85** [comment]
Any update on this? I'm having the same issue.

**Comment by cfjedimaster** [comment]
Not yet - haven't had time to work on it.

**Comment by cfjedimaster** [comment]
Fixed.
