### ISSUE TITLE
W3C Validator Extension is not working

### ISSUE THREAD

**Issue by emymew** [cfjedimaster/brackets-w3cvalidation#36]
I have installed W3C Validator extension through brackets but in the bottom right corner the check/error mark is not showing how to I turn it back on???
![w3c](https://cloud.githubusercontent.com/assets/12375547/14584486/a814d738-03fc-11e6-8858-5422d129db9b.JPG)
![w3c_2](https://cloud.githubusercontent.com/assets/12375547/14584485/a8130340-03fc-11e6-9ab0-500dc5ce8b60.JPG)

**Comment by emymew** [comment]
Here is a screen shot where I intentional take out the end closing tag for <head> and it is not showing that there is an error on the page
![uncomplete_head_element_w3c](https://cloud.githubusercontent.com/assets/12375547/14624768/6cde2862-0592-11e6-9ab1-8268328cf1b5.JPG)

**Comment by cfjedimaster** [comment]
If you open up the debugger, do you see anything?

**Comment by emymew** [comment]
I have an option to Enable Node Debugger, otherwise I have to use my
Developer Tools on Brackets to show any errors.

**Comment by cfjedimaster** [comment]
Right - that's what I meant. Did you see any errors in devtools?

**Comment by emymew** [comment]
I see 11 warnings.
One warning say,
**PreferencesManager.convertPreferences() has been deprecated. Please upgrade to the current Preferences system (https://github.com/adobe/brackets/wiki/Preferences-System#conversion-from-the-pre-36-preferences-system)**
And 10 other messages that say,
**Deprecated: Do not use $().on/off() on Brackets modules and model objects. Call on()/off() directly on the object without a $() wrapper.**

**Comment by cfjedimaster** [comment]
I honestly don't know what to say now. If you don't see errors - and it just isn't validating - then.... I don't know. We've got the same version for sure. Try looking at the Network panel, filter on XHR, type w3 in the filter field to see if you can see a call to the validator. 

![image](https://cloud.githubusercontent.com/assets/393660/14676499/85d2c612-06c2-11e6-9404-0b21e4df665d.png)

**Comment by emymew** [comment]
So my teacher told me all I have to do is uninstall Brackets then go to (C:\Users\[your user name goes here]\AppData\Roaming\Brackets) and delete the folder for brackets. Then reinstall, and now it's working. I am a little to all this tech stuff didn't realize that I had to do that

**Comment by cfjedimaster** [comment]
Boggle - I'm not new to this tech stuff and I wouldn't have thought that was necessary. Just glad you got it.

**Comment by MrBoudewijn** [comment]
Oke, which I knew that 16 hours ago... ;P

"As of November 1, 2016, I've decided to remove my extension from the Brackets registry. Multiple users have found themselves banned from the w3c API because Brackets, for whatever reason, sends a large number of API requests. I was never able to figure out why. It could be my fault, it could be Brackets' fault. As I don't use, or recommend, Brackets anymore, I'm not really working on this extension. If someone wants to take a stab at fixing it, be my guest."

**Comment by viollett** [comment]
how do i install w3c validator in brackets kindly help

**Comment by viollett** [comment]
any online link i should use?

**Comment by cfjedimaster** [comment]
@viollett this is not a general support forum for Brackets. Please use the normal method for installing extensions. If you have trouble, see: https://github.com/adobe/brackets/wiki/Troubleshooting#extension-install.
