### ISSUE TITLE
Still the best extension for HTML. Thank you note.

### ISSUE THREAD

**Issue by jluisgarcia** [cfjedimaster/brackets-w3cvalidation#40]
I never had problems with being banned for making too many http requests.
Dont understand how it is different to some other people.
This is BY FAR the best extension for HTML validation.
Visual Studio Code's intenal validation is not as good WC3's
The same could be said for CSSLint validation.
I still use Brackets as a backup validation tool. Only because of your neat extensions.
Thanks Raymond for your effort in the past.

**Comment by cfjedimaster** [comment]
You are most welcome. :)
