### ISSUE TITLE
Consider using Brackets linting API

### ISSUE THREAD

**Issue by peterflynn** [cfjedimaster/brackets-w3cvalidation#6]
Brackets Sprint 31 will introduce a new, clean API for linting providers:
https://github.com/adobe/brackets/wiki/Release-Notes:-Sprint-31#newimproved-extensibility-apis

Using the new API could potentially improve the UI of this extension -- and allow it to benefit from future linting functionality upgrades automatically.

**Comment by DannyCork** [comment]
This is how it's done now right ?

**Comment by cfjedimaster** [comment]
Yep - I had to wait for async support - but it does.
